# Generated by Django 3.0.5 on 2020-05-06 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.constants
import main.managers
import main.models.subject


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', main.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('x_pos', models.SmallIntegerField(blank=True)),
                ('y_pos', models.SmallIntegerField(blank=True)),
                ('hp', models.SmallIntegerField(default=100)),
                ('is_dead', models.BooleanField(default=False)),
                ('move_speed', models.SmallIntegerField(default=5)),
                ('weapon', models.CharField(choices=[('bow', 'bow'), ('short_sword', 'short sword')], default='short sword', max_length=255)),
                ('type_of_subject', models.CharField(choices=[('HUMAN', 'human'), ('ELF', 'elf'), ('HALF_ELF', 'half_elf'), ('GNOME', 'gnome'), ('DWARF', 'dwarf'), ('GOBLIN', 'goblin')], default=main.constants.SubjectTypeEnum['HUMAN'], max_length=50)),
                ('color', models.CharField(choices=[('RED', 'red'), ('BLUE', 'blue'), ('GREEN', 'green')], default=main.models.subject.default_color, max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('turn_number', models.IntegerField(default=0)),
                ('now_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_player', to='main.Subject')),
                ('players', models.ManyToManyField(to='main.Subject')),
            ],
        ),
    ]
