# Generated by Django 3.0.5 on 2020-04-24 18:02

from django.db import migrations, models
import django.db.models.deletion
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200405_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('object', main.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Game_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('turn_number', models.IntegerField()),
                ('now_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_player', to='main.User')),
                ('players', models.ManyToManyField(to='main.User')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
