# Generated by Django 3.0.5 on 2020-04-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200424_1729'),
        ('main', '0003_auto_20200424_1802'),
    ]

    operations = [
    ]
