# Generated by Django 3.0.5 on 2020-04-24 19:58

from django.db import migrations
import main.managers


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('main', '0004_merge_20200424_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_room',
            new_name='GameRoom',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.managers.UserManager()),
            ],
        ),
    ]
