# Generated by Django 3.0.5 on 2020-04-24 21:16

from django.db import migrations


def forwards_func(apps, *args):
    GameRoom = apps.get_model("main", "GameRoom")
    GameRoom.objects.create(name="Roll 21", turn_number=0)


def reverse_func(apps, *args):
    GameRoom = apps.get_model("main", "GameRoom")
    GameRoom.objects.get(name="Roll 21").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200424_1958"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
