# Generated by Django 3.0.5 on 2020-04-26 19:26

from django.db import migrations, models
import main.constants
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_main_gameroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('ColorEnum.RED', 'red'), ('ColorEnum.BLUE', 'blue'), ('ColorEnum.GREEN', 'green')], default=main.models.default_color, max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_subject',
            field=models.CharField(choices=[('SubjectTypeEnum.HUMAN', 'human'), ('SubjectTypeEnum.GOBLIN', 'goblin')], default=main.constants.SubjectTypeEnum['HUMAN'], max_length=50),
        ),
    ]
