# Generated by Django 3.0.5 on 2020-04-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_main_gameroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='turn_number',
            field=models.IntegerField(default=0),
        ),
    ]
