# Generated by Django 3.0.5 on 2020-04-26 19:30

from django.db import migrations, models
import main.constants
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200426_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('RED', 'red'), ('BLUE', 'blue'), ('GREEN', 'green')], default=main.models.default_color, max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_subject',
            field=models.CharField(choices=[('HUMAN', 'human'), ('GOBLIN', 'goblin')], default=main.constants.SubjectTypeEnum['HUMAN'], max_length=50),
        ),
    ]
