# Generated by Django 3.0.5 on 2020-04-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200426_1930'),
        ('main', '0007_auto_20200424_2220'),
    ]

    operations = [
    ]
