# Generated by Django 3.0.5 on 2020-05-04 20:37

from django.db import migrations, models
import django.db.models.deletion
import main.constants


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20200426_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='move_speed',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='weapon',
            field=models.CharField(choices=[('bow', 'bow'), ('short_sword', 'short sword')], default='short sword', max_length=255),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='now_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_player', to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(to='main.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type_of_subject',
            field=models.CharField(choices=[('HUMAN', 'human'), ('ELF', 'elf'), ('HALF_ELF', 'half_elf'), ('GNOME', 'gnome'), ('DWARF', 'dwarf'), ('GOBLIN', 'goblin')], default=main.constants.SubjectTypeEnum['HUMAN'], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
